### ISSUE TITLE
Passphrase Needed

### ISSUE THREAD

**Issue by pjv** [mikedilger/gossip#189]
I went into Keys and entered my nsec1 along with a password for it. Everything seemed to work fine.

I quit gossip and then restarted it and I am getting the prompt that I need to setup my identity to post. I go into Keys and the top box looks like this:

<img width="411" alt="SCR-20230202-cbz" src="https://user-images.githubusercontent.com/327716/216357870-e6c9edc2-bbec-4b2f-990c-e8150c0c62ad.png">

I type in the password I originally saved with the nsec1 and click “Unlock Private Key” and the GUI gives me a beachball and gossip freezes. (Nothing in the log).

I’m running on 0b51467.

**Comment by mikedilger** [comment]
Ok. How long do you get the "beachball" for?  How powerful is your computer?  How much memory does it have?

The reason I ask is that we use `scrypt` in order to slow down password-guessing attacks at your encrypted key.  scrypt is both memory and cpu intensive, making it hard to crack your encrypted key even on dedicated ASICs.  We use N=2^18, which takes about 256 MB and about 1/2 of a second on most modern desktops.

If you are getting this "beachball" for a very long time, then maybe there is a different problem.

**Comment by pjv** [comment]
I let the beachball spin for at least 20 seconds before i ctrl-c’d gossip. My machine is a pretty beefy iMac pro.

<img width="244" alt="SCR-20230202-is9" src="https://user-images.githubusercontent.com/327716/216431345-6f9a2417-3f97-42b7-b85f-fbad081bafd2.png">

**Comment by mikedilger** [comment]
So far I could not reproduce.  Running on 0b51467ffa2c7069629c49e5efbc3eddc3670370 after moving my database (to get a new one), I entered an nsec1 with a password, it worked, I closed it. Reopened it and went to enter my password and everything worked fine.  I tried it 2 more times.  I could not reproduce.

In overlord/mod.rs line 575 and below, it does the UnlockKey command.  Therein it locks the signer a few times, and settings once.  The 'You' page accesses the signer in many places, and does so many times per second, but it keeps unlocking it too (each lock quickly returns something that is not borrowed) so the UnlockKey command should be able to make progress.

Did this just happen once or does it happen every time?  If it is repeatable, maybe I could get you to do some debugging for me?

**Comment by pjv** [comment]
Updated to 4155471 and same problem. I also moving the db out of the way to start fresh and followed your exact procedure above and got the same thing.

It is repeatable - happens every time.

I’m looking at line 575 of `src/overlord/mod.rs`.

**Comment by mikedilger** [comment]
I just pushed a branch 'debug189'.  Can you run it and pipe the output through "grep DEBUG189" and send me the results?

**Comment by pjv** [comment]
Pulled and checked out the debug branch, recompiled, ran it (at b37e9ff) like so:

`./target/release/gossip |grep DEBUG189`

Then went to the You page and pasted my pw in and clicked the button. GUI immediately froze up, then beachball. Zero output in the terminal.

**Comment by mikedilger** [comment]
Interesting. So it couldn't lock the signer right from the get-go.  I wonder who is holding the lock?

Maybe rust isn't dropping where I think it should drop, pull the branch and try again. And what version of rust are you using to compile?

**Comment by pjv** [comment]
````
brew info rust
==> rust: stable 1.66.1 (bottled), HEAD
````
now at f8bb8d1

same, no debugging output.

I also ran it without the piped grep and there is normal output but nothing with a label on it and nothing related to what i think you probably put in there for either the key unlock or the GUI.

**Comment by mikedilger** [comment]
I'm sorry I couldn't fix this quickly. I hope I'm not bothering you too much. But if you could, I've pushed a new branch called 'new-signer' which uses a fine-grained interior locking structure instead.  Wanna try that?

**Comment by pjv** [comment]
no worries.

So new-signer is an improvement. It’s still not unlocking my private key but it’s not crashing anymore and it logged this:

`ERROR Nostr: Encryption/Decryption Error`

**Comment by mikedilger** [comment]
Generally that means your passphrase isn't correct.

**Comment by pjv** [comment]
OK, that was a good clue.

So I tried clicking the button with a blank passphrase and that unlocked me. So in the past when I put in the key in the first place along with the passphrase it must not have used the passphrase at all. I’ll re-do it now with passphrase again.

…or not. Now I can’t delete the identity - freezes the GUI and beachballs me. I have been able to delete in the past.

BTW when the GUI is frozen, gossip is still logging things about relays and whatnot, so it’s only the front end that is choking.

Any chance you can make the delete identity button work so I can re-try without nuking my db?

**Comment by mikedilger** [comment]
Hey it just did it to me too!  Now I can debug this part myself.

**Comment by mikedilger** [comment]
ok pull new-signer and try again

**Comment by pjv** [comment]
Working. 👍
