### ISSUE TITLE
panic when going through new user flow

### ISSUE THREAD

**Issue by jeremyd** [mikedilger/gossip#191]
I'm going through the new user flow.  Here's what I encountered after the step to add myself as following and pull.  The other thing I noticed on the relays page, there is no save button... so maybe that's why?  I can screenshot it if you like..

INFO Done picking relays: Unable to make further progress.
thread 'main' panicked at 'byte index 64 is out of bounds of `npub1sn0wdenkukak0d9dfczzeacvhkrgz92ak56egt7vdgzn8pv2wfqqhrjdv9`', src/ui/mod.rs:435:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mikedilger** [comment]
Thanks for the bug report. Will fix.

The relays page saves each change immediately.  The UX is terribly inconsistent right now. Sorry about that.

**Comment by mikedilger** [comment]
I'm impressed you were able to create such a panic for a couple of reasons.  Byte index 64 wasn't accessed (the 64 in range notation is 1 beyond the last byte).  And I'm not understanding where a too-short PublicKeyHex was created.

I might change the `PublicKeyHex` type to keep it's interior private and expose a to_str() and try_from_str(), and require it to be 64 hex characters.  Then I'd need a `PublicKeyHexPrefix` type too.  Sounds like a lot of work though.

**Comment by jeremyd** [comment]
looks fixed in d9c68cb6f01385725d2715ccb8d0c8e20429f429

**Comment by mikedilger** [comment]
Doesn't actually fix properly though. Just avoids the panic. Somehow the value is invalid and I'd like to find out which part of the code created the invalid value.  And I could do that by strengthening the types.

**Comment by jeremyd** [comment]
> I'm impressed you were able to create such a panic for a couple of reasons. Byte index 64 wasn't accessed (the 64 in range notation is 1 beyond the last byte). And I'm not understanding where a too-short PublicKeyHex was created.
> 
> I might change the `PublicKeyHex` type to keep it's interior private and expose a to_str() and try_from_str(), and require it to be 64 hex characters. Then I'd need a `PublicKeyHexPrefix` type too. Sounds like a lot of work though.

notice who's key it is?  it's a vanity key..

**Comment by mikedilger** [comment]
Oh crap I didn't notice it was passing in an npub.  That's what is wrong.  Ok, I can find this... hang on ...

**Comment by mikedilger** [comment]
Heh, someone tagged Snowden but put an 'npub' in the tag rather than the appropriate 'hex'.

**Comment by jeremyd** [comment]
> Heh, someone tagged Snowden but put an 'npub' in the tag rather than the appropriate 'hex'.

yup!  good to know, i thought i might be going crazy from this same type of thing.. the type3's don't have much validation of what the tag can say on the relay side it seems.

**Comment by jeremyd** [comment]
I have also seen tags with nip05 names.. as the pubkey

**Comment by mikedilger** [comment]
I will be fixing with this, probably later tonight:
https://github.com/mikedilger/nostr-types/commit/4824e5bc9498049b3264d2e3ee64672ba6e48118

**Comment by jeremyd** [comment]
funny story, this was an event3 turns out I created.. whoops.  Breakin' stuff :) Got that fixed now.  Interesting the contact list can be so fluid, If a client were to decide they want to support more than hex, the relays seem to allow for it. (same with sending dupes, they accept it and prune it usually.. but maybe not always)

**Comment by mikedilger** [comment]
Breaking stuff is a good way to test what is breakable so we can fix it.

**Comment by mikedilger** [comment]
This was done a few days ago.
