### ISSUE TITLE
Direct Messages not showing up in Inbox>Direct Replies Only

### ISSUE THREAD

**Issue by InnocuousFinch** [mikedilger/gossip#309]
Under `Settings > What Posts To Include` I have checked the box for `Show Direct Messages`, saved changes, and am still not seeing them anywhere in Gossip.

**Comment by mikedilger** [comment]
They will be in your Inbox mixed in with all the other posts and say DIRECT MESSAGE on them.  You can't reply to them.  We don't support creating these, just viewing them.

**Comment by InnocuousFinch** [comment]
I attempted to send a direct message to myself to see if it'd come through, but maybe those get filtered out?

Is support for creating and viewing Direct Messages as a separate menu item on the roadmap?

**Comment by mikedilger** [comment]
It subscribes to DMs that are have a 'p' tag that matches your pubkey... e.g. ones that are addressed to you, whether you created it or not.  It pulls them from your 'Read' relays, so make sure that other client wrote them to one of those relays.  Beyond that, I have no idea why they would not show up.  They work for me right now.

I don't want to support DMs because they are not secure, but pretend to be, and I think that is highly likely to confuse people into thinking they are secure.  I'm waiting for a better DM NIP to come around, but in the meantime I wanted to see what people sent to me so I implemented viewing them.

**Comment by InnocuousFinch** [comment]
That makes sense, @mikedilger, closing out this issue. 

For FWIW, I've confirmed that the DMs to myself do show up, but they only show up under `You > Notes>>`

All other DMs show up under `Feed > Inbox > Everything you are Tagged On`, and are _not_ included in `Direct Replies Only` Inbox option.

**Comment by mikedilger** [comment]
Ok well that sounds like a mistake/bug for them not to be under Direct Replies Only.  I'll reopen this so that can get fixed.

**Comment by mikedilger** [comment]
Done.

**Comment by InnocuousFinch** [comment]
I've compiled the latest from master branch, and am still not seeing any changes from what was initially reported.
